# Generated by Django 2.1.2 on 2018-11-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_release_id', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256)),
                ('cover_url', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('release_type', models.CharField(max_length=256)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.Artist')),
            ],
        ),
    ]
