# Generated by Django 2.1.2 on 2018-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='access_token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
