# Generated by Django 2.1.1 on 2019-01-26 21:43

from django.db import migrations

def combine_names(apps, schema_editor):
    from django.contrib.auth.models import User
    for user in User.objects.all():
        if user.social_auth.count() > 1:
            user.social_auth.filter(provider='deezer').delete()
            user.integration_set.filter(identifier='deezer').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20181214_1019'),
    ]

    operations = [
        migrations.RunPython(combine_names, reverse_code=lambda x, y: x),
    ]
