# Generated by Django 2.1.1 on 2019-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_auto_20190126_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='integration_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
