# Generated by Django 2.1.7 on 2019-03-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_release_integration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
    ]
