# Generated by Django 2.1.2 on 2018-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='connect_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
